### ISSUE TITLE
Rethink src/helpers/responsiveness

### ISSUE THREAD

**Issue by endymion1818** [zopaUK/react-components#106]
**Why**
Responsive sizes are not consistent with sizes used in the designs or the rest of RCL

**What**
Change 
```
const sizes = {
  desktop: 1280,
  phone: 600,
  tablet: 720,
};
```
to
```
const sizes = {
    l: 992,
    m: 768,
    s: 576,
    xl: 1200,
    xs: 0,
};
```
or similar

**Comment by lluia** [comment]
I think this change is pretty aggressive as it has the potential to break the layout on the most client of this library 😨

I beleive
```js
const sizes = {
    l: 992,
    m: 768,
    s: 576,
    xl: 1200,
    xs: 0,
};
```
it's the specs you get in **Shopfront** @endymion1818 ?

I think it's fair for **Shopfront** to have different breakpoints due to the intricacy of the layout in certain pages.

I think though all the other apps are sticking to this one?
```js
const sizes = {
  desktop: 1280,
  phone: 600,
  tablet: 720,
};
```

**Comment by endymion1818** [comment]
https://github.dns.ad.zopa.com/zopaUK/shopfront/blob/master/src/components/tokens.ts#L35

Going forward we're gooing to be using these breakpoints, still quite different though.

https://www.zopa.com/borrowing-power

Without one of those extra breakpoints we couldn't have made the layout on tablet for this page.

I understand where you're coming from with Shopfront being a unique beast; but we are also mindful that we want to be as close to the react-components as possible, and uniform with the rest of Zopa.

**Comment by thegrinder** [comment]
what's the exact reasoning behind picking these breakpoints? When building our grid I mimicked bootstrap grid and there is some logic behind it https://github.com/twbs/bootstrap/issues/14894

**Comment by lluia** [comment]
@endymion1818 @thegrinder I'm gonna close this in the next few days as I don't see much activity related to it 😴

In case we think it's still relevant lets try to materialise it into formal API suggestions 👍

**Comment by endymion1818** [comment]
OK, happy to close this issue. I've recently got word of a 3rd design iteration, we can hopefully standardise our approach across all platforms then.
