### ISSUE TITLE
Accordion spacing

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#113]
The spacing between the title and the copy is too tight could we have it spaced out further?

![Screenshot 2019-09-27 at 12 02 58](https://user-images.githubusercontent.com/3974301/65764976-d9bfb980-e11e-11e9-9b16-0d56b89e724f.png)

**Comment by thegrinder** [comment]
@moshie thanks for creating this issue. The way the accordion was built was with flexibility in mind and that's why there is no default padding/margin there. However, nothing stops you from wrapping the content in a div that has a bit of spacing.
