### ISSUE TITLE
Accordion no-js fallback

### ISSUE THREAD

**Issue by endymion1818** [zopaUK/react-components#114]
The accordion renders in a closed state when JavaScript is disabled, meaning the content is not visible.

<img width="685" alt="Screenshot 2019-09-27 at 13 50 32" src="https://user-images.githubusercontent.com/2216344/65770404-eef01480-e12d-11e9-94e7-935f94fb9bbd.png">

Although we don't expect users to have this behaviour, it is useful for SEO crawler first-pass and for other potential / existing customers who are spending time abroad and are on a difficult or costly connection.

The initial state should be changed to open so that prerendered apps can still view as much content as possible without JavaScript.

**Comment by lluia** [comment]
Another minor thing I can &nbsp;👀 is that the arrow should be aligned to the top not the center of the text when the title has more than one line?

**Comment by lluia** [comment]
To achieve having the accordions open in **NO JS** is going to be tricky:

https://github.com/zopaUK/react-components/blob/master/src/components/hooks/useAccordion/useAccordion.ts#L65

https://github.com/zopaUK/react-components/blob/master/src/components/hooks/useAccordion/useAccordion.ts#L132

By default, we don't mark any `<Accordion.Section />` as `active` and only change that once the user press on the corresponding `<Accordion.Header />`.

It makes sense, as when rendering the view you don't want the accordions to be open and then collapse them 😌

**Comment by endymion1818** [comment]
I don't know if that is as bad as not being useable at all ... or the content not being available to search engines ...

**Comment by lluia** [comment]
I don't say is not possible, just that's tricky 🙃 

Somebody needs to find time to wrestle with it 😉 ( PRs welcome 👍🏻 )

**Comment by lluia** [comment]
@endymion1818 @thegrinder I'm gonna close this in the next few days as I don't see much activity related to it 😴

In case we think it's still relevant lets try to materialise it into formal API suggestions 👍

**Comment by endymion1818** [comment]
I still think it's relevant but this whole FAQ thing is being revisited so there may be another solution incoming ... I'm still going to have a bash at it when I get the chance because I think it's important to our users.

I'll close for the time being @lluia, and re-open it when I get round to picking it up.
