### ISSUE TITLE
Accordion Chevron duplicate id attribute

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#115]
The accordion pulls in an SVG chevron for each child in the accordion.
Each SVG has multiple id attributes which are duplicated for each instance.
Where the id property is not needed it needs to be removed.

![Screenshot 2019-09-30 at 10 28 41](https://user-images.githubusercontent.com/3974301/65866829-6a8bd480-e36d-11e9-89c2-b828a7f59ce8.png)

**Comment by lluia** [comment]
Cools, I think this one is pretty straightforward to fix 😊 , feel free to open a PR or I'll do later 💆🏻‍♂️

**Comment by lluia** [comment]
Fixed and deployed on the above PR ☝️
