### ISSUE TITLE
Add alias to import components

### ISSUE THREAD

**Issue by dfvalero** [zopaUK/react-components#121]
I see that there is an alias config for react-styleguidist, we can easily add aliases for the "real" code editing the typescript config.

It will be a good option to avoid all the imports like `import whatever from '../../../whatever'`

**Comment by lluia** [comment]
Coolios for me, lets wait for @poteirard feedback 💬 and whether he hit any issues on the past related to it 👍🏻

**Comment by dfvalero** [comment]
Looks like it can't be done for now, because react-scripts doesn't accept baseUrl and paths params in the tsconfig file, so we won't be able to run tests :(

**Comment by poteirard** [comment]
Alias is something we looked into it in the past. 

We decided to don't go for it since it requires additional config in some places, tsconfig, rollup, react-scripts... and it's not worth for this "nice to have"

**Comment by lluia** [comment]
Coolios, I'll be closing this for now and we can always re-visit later if we want 👍🏻
