### ISSUE TITLE
`as` prop typings

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#123]
## Description

Currently Components employing the as property have their types set to `React.AnchorHTMLAttributes<HTMLAnchorElement>` this is missing the as type which causes the following attached error:

![Screenshot 2019-10-14 at 11 52 00](https://user-images.githubusercontent.com/3974301/66750561-b027c180-ee84-11e9-81ac-12365b1e4791.png)

**Comment by lluia** [comment]
I was having a look at this recently, there's a [work in progress branch](https://www.theguardian.com/world/2019/oct/14/poland-populist-law-and-justice-party-increases-majority).

One of main issues is that `as` is too dynamic for Typescript 🙄 , hence the only solution I can think of right now is to get it typed as `any` 😓

**Comment by moshie** [comment]
@lluia your branch link goes off to a news article :P

**Comment by lluia** [comment]
Much Lol, I've updated the link 😂

**Comment by lluia** [comment]
Recently we're [hitting issues](https://github.com/zopaUK/react-components/issues/129) were some components don't support a particular usage of `as`.

One of the reasons is that many of the components on this library were developed before the [`as` polymorphic prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) was introduced in `styled-components@4`.

I think we need to re-visit each component and re-think which typings of `as` make sense for it, 
this property being highly dynamic can lead to [some struggles with TS](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30117).

**Comment by lluia** [comment]
Closing, in principle this issue was tamed down in #127  and #148. 

However, we keep an eye in case we see new issues related to this 🤞🏻
