### ISSUE TITLE
Secondary Button Border disappears

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#129]
When defining a secondary styled button as an anchor tag the button loses its border.

This is caused by the `:enabled`

This is a screenshot of the broken button with `as="a"` property set. as you can see the border is missing.

![Screenshot 2019-10-28 at 08 19 09](https://user-images.githubusercontent.com/3974301/67662687-cab96a80-f95b-11e9-9aba-1991181ed785.png)

**Comment by poteirard** [comment]
I think for anchors we use the `<Link />` components. Not sure if it will fit your needs, you can finde it here https://zopauk.github.io/react-components/#/Components/Atoms/Link

**Comment by moshie** [comment]
Unfortunately the link component doesn't carry the same styles as the button and we would prefer not to duplicate the button styling in shopfront.

The link component won't let us use `as={Button}` because this fails ts type checking
```
Property 'as' does not exist on type 'IntrinsicAttributes & ILinkProps & { children?: ReactNode; }'
```

**Comment by lluia** [comment]
@moshie types fix is on the way.

I advise you thought to be spare with the use of `as`, specially when you try to render a component through it:
```js
<Link as="button" />
<Link as={Button} /> // vs
```

`as`, while being very convenient is quite TS non-friendly due to [how dynamic it can become](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30117). Hence I recommend you use it to override the **HTML tag** rather than the component being rendered.

Can you ellaborate what's your use-case to do something like: `<Link as={Button} />` or `<Button as="a" />`? I think is better if we stick to render `<Button />` as `<button />` if we can?

**Comment by lluia** [comment]
The current `<Button />` implementation was done before even [`as` was available on `styled-components`](https://www.styled-components.com/docs/api#as-polymorphic-prop) and hence was done assuming `<Button />` would always render `<button />`.

Hence we should treat `<Button />` for now as non `as` friendly 😉 

If we want to make it `as` friendly though we need to decouple then the [styling to the `
enabled` attribute](https://github.com/zopaUK/react-components/blob/master/src/components/atoms/Button/Button.tsx#L120).

We might want to lock `as` on `<Button />` to `<button />` as something like `<Button as="span" />` might not be what we want.

**Comment by dfvalero** [comment]
But this issue raises up another missing feature:
- The border is missing for a secondary disabled button `<Button styling="secondary" disabled>Text</Button>`

**Comment by lluia** [comment]
Good catch @dfvalero 💯, we probably can already address this issue while we think what to do with `as` 👍

**Comment by lluia** [comment]
Speaking with @moshie we agreed it makes sense to be able to render `<Button />` as `a | button | span`.
- `<button />` should be what's rendered by default
- `<a />` handy to make the CTA **SEO** friendly in some scenarios
- `<span />` to make  the entire CTA "clickable" not just the button

So this is ready to work as well 👍🏻

**Comment by moshie** [comment]
FYI, This also breaks the hover state

**Comment by dfvalero** [comment]
With this solution We will lose the `disabled` styles when we render `<Button />` as `a | span` because those HTML elements doesn't understand `disabled` attribute.

**Comment by moshie** [comment]
That should be fine as we would never have scenarios where an `a | span` would be disabled
