### ISSUE TITLE
Bot for updating dependencies 

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#13]
Would be nice to have a bot that opens PR for dependency updates, like:

- [Renovate](https://renovatebot.com/)
- [Greenkeeper](https://greenkeeper.io)

Not sure if this is in **work in progress** already, I thought it's good to open an issue to keep track of it 👍🏻

**Comment by lluia** [comment]
Speaking with @poteirard, we identified the following two issues around adding **automated dependency updates**:

### Unexpected updates 😪

Some of the dependencies are considered _"delicate"_ to update. For instance, upgrading `react-scripts` might break `react-styleguist` without us noticing.

First, we would need to identify those _"delicate"_ dependencies and then make the dependency bot [ignore them](https://renovatebot.com/docs/configuration-options/#ignoredeps), relying on us to update them manually as we see fit.
 
### Update side effects 🥴

Updating some of our dependencies might result in _visual_ or _behavioral_ changes in some of the components exposed in this library. 

We might not catch those changes. We currently mostly have _snapshot tests_ with some _unit tests_,  here and there but first, we think would be worth to invest on a stronger suite by:

- making a [visual screenshot](https://docs.cypress.io/api/commands/screenshot.html#Syntax) of the output rendered by each component
- testing behaviour in the browser when needed too

**Comment by poteirard** [comment]
Closing this since we already have security upgrades (provided by Github).

Reopen in case we want something more :)
