### ISSUE TITLE
Dependencies cleanup 🧼

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#134]
#### 1. `acorn` / `acorn-jsx`

We have [these dependencies declared on `package.json`](https://github.com/zopaUK/react-components/blob/master/package.json#L60-L61) but they're not used within the project.

It'll be good to investigate how they came there and experiment in a **pull request** whether it's safe to remove them 💆🏻‍♂️

#### 2. `@sematinc-release/github`

We're using [`"resolutions"` to pin the version of `@semantic-release/github`](https://github.com/zopaUK/react-components/blob/master/package.json#L94-L96). We don't have context on why, so we need to investigate how it came there and whether it's safe to remove through a PR.

**Comment by poteirard** [comment]
Found it here: https://github.dns.ad.zopa.com/zopaUK/react-components/search?q=acorn&type=Commits
> acorn and acorn-jsx have been installed as it fixes a known bug
github.com/styleguidist/react-styleguidist/issues/1278
