### ISSUE TITLE
Type `<Link color />` properly

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#139]
The `color` prop on `<Link />` is currently typed as `any`, however this is the [type it should point to](https://github.com/zopaUK/react-components/blob/master/src/constants/colors.ts#L2), which represents the colour values we expect to be supplied.

The reason to be typed as `any` is that it was conflicting with the `color` definition of `<Text />` ( _as it used to extend it_ ), now that `<Link />` just extends `styled.a` we might not have this problem anymore.

**Comment by moshie** [comment]
Do we have too hard define the string values can we not just define it as a string?
Sometimes we find that links are colours not defined in this union type.

I can give an example in a PM.

**Comment by lluia** [comment]
I think this was [fixed on *v3*](https://github.com/zopaUK/react-components/blob/master/src/components/atoms/Link/Link.tsx#L10) but I forgot to close the issue 😅 

In *v4* is gonna be even less of an issue given we [only gonna have two colours](https://github.com/zopaUK/react-components/blob/milestone/4.0.0/src/components/atoms/Link/Link.tsx).
