### ISSUE TITLE
NavbarDropdown renderItem/renderOpener returning ref causes warning

### ISSUE THREAD

**Issue by dfvalero** [zopaUK/react-components#143]
NavbarDropdown `renderItem` and `renderOpener` attributes are returning two methods called `getItemsProps` and `getOpenerProps`. If we want to use these methods to render a Navbar.Link it will cause a warning because `getItemProps` and `getOpenerProps` are returning `ref`.

Code:
```
<Navbar.Dropdown
  id="navbar-help-dropdown"
  ariaLabel="Navbar Help Dropdown"
  items={[{ label: 'Profile', href: getProfilePath() }, { label: 'Logout', onClick: onLogout }]}
  renderOpener={({ open, getOpenerProps }) => (
    <Navbar.Link href="#" withChevron open={open} {...getOpenerProps()}>
      {getProfileName(userDetails)}
    </Navbar.Link>
  )}
  renderItem={({ item: { label, href, onClick }, getItemProps }) => (
    <Navbar.Link href={href} onClick={onClick} {...getItemProps()} style={{ paddingBottom: '10px' }}>
      {label}
    </Navbar.Link>
  )}
/>
```

Warning:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Possible solution:
- Clean the `ref` property from the `getItemProps` and `getOpenerProps` methods.

We implemented a fix in the ZEOSHub repository to avoid this issue:

```
const refClean = (props) => {
  const {ref, ...newProps} = props;
  
  return newProps;
};
```

With this method you can use the NavBar.Link without the warning:

```
<Navbar.Link href="#" withChevron open={open} {...refClean(getOpenerProps())}>
    {getProfileName(userDetails)}
</Navbar.Link>
```

**Comment by poteirard** [comment]
Sounds a clean solution to me. Let's see what the master @thegrinder says about this.
