### ISSUE TITLE
Tap targets in footer not appropriately sized

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#146]
These tap targets for these links Blog, Careers & Press team in the footer are making lighthouse unhappy. 

We strive for 100 nothing but green 🥇 

![Screenshot 2019-12-04 at 13 46 32](https://user-images.githubusercontent.com/3974301/70147881-1074fb80-169d-11ea-9a3c-83100be682f3.png)

**Comment by lluia** [comment]
I believe this one is easy enough to either increase the `font-size` or `padding` around them 📐

@moshie or @endymion1818 wanna give it a go? I'm under a _types armageddon_ currently 🔥 😄

**Comment by endymion1818** [comment]
"types armageddon" 🤣

**Comment by lluia** [comment]
Addressed on the latest version: `2.7.2` 👍🏻

**Comment by endymion1818** [comment]
👏  thanks @lluia
