### ISSUE TITLE
Export icons

### ISSUE THREAD

**Issue by poteirard** [zopaUK/react-components#15]
@grabbeh Just reported this issue:

> I think https://github.com/zopaUK/react-components/blob/master/src/index.ts needs to export all the icons (I think Chevron, Facebook etc are missing?) - I tried import { Chevron } at the weekend but it didn't seem to work.

**Comment by lluia** [comment]
@poteirard I'm actually addressing this in my branch, hopefully, I can open a PR this morning 👍 👌

**Comment by lluia** [comment]
Closing as this was fixed on the above PR ☝🏻
