### ISSUE TITLE
Form.TextField required inputProps

### ISSUE THREAD

**Issue by dfvalero** [zopaUK/react-components#152]
Actually, the component `Form.TextField` needs an inputProps property (it can be an empty object). This will generate code like:

`<Form.TextField label={label} name={name} size="long" inputProps={{}} />`

or (redundant):

`<Form.TextField label={label} name={name} size="long" inputProps={{ name }} />`

Looks like there is a small mess with the interfaces for Form.TextField, TextField and other components related to Form.

Some have name as a required prop and in others name is optional.

We need to discuss how we improve the typing for all the Form related components.

**Comment by lluia** [comment]
This is [being addressed](https://github.com/zopaUK/react-components/pull/231) on our next milestone 👍
