### ISSUE TITLE
`style={{}}` attribute not possible on `<FlexCol/>` element

### ISSUE THREAD

**Issue by endymion1818** [zopaUK/react-components#154]
We often use inline styles to extend the `<FlexCol/>` element for Shopfront. However, updating to the newer version results in the following TS error:

```
Property 'style' does not exist on type 'IntrinsicAttributes & IFlexColProps & { children?: ReactNode; }'
```

**Comment by lluia** [comment]
Ahhh so it seems I missed this one [in my last PR](#148), in theory all components should be accepting `className` and `style`.

As you point, currently [the interface is not extending the native HTLM element types](https://github.com/zopaUK/react-components/blob/master/src/components/layout/FlexCol/FlexCol.tsx#L91) and hence is missing these attributes.

I'll open a quick fix today, good catch 💯

**Comment by lluia** [comment]
@endymion1818  PR for it, **codecov** is complaining but I don't think is a blocker...

**Comment by endymion1818** [comment]
Thanks so much @lluia 🎉

**Comment by lluia** [comment]
@endymion1818 

I merged the PR, you can now update the library and you shouldn't hit the problem anymore 🤞
