### ISSUE TITLE
Upgrade  `react-styleguidist@11`

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#158]
Supports TS out of the box, so we might not need anymore `react-docgen-typescript`.

See  👀
https://github.com/styleguidist/react-styleguidist/pull/1500
https://github.com/styleguidist/react-styleguidist/pull/1514/files

**Comment by poteirard** [comment]
It will be present in the upcoming major version [react-styleguidist@11](https://github.com/styleguidist/react-styleguidist/milestone/18)
