### ISSUE TITLE
Default <Spinner /> doesn't match stated defaults

### ISSUE THREAD

**Issue by grabbeh** [zopaUK/react-components#17]
Docs state that default backgroundColor is teal (and is stated to take up 3/4 of the circle). However, standard spinner without any added props only has 1/4 of the circle taken up as teal.

In https://github.com/zopaUK/react-components/blob/master/src/components/atoms/Spinner/Spinner.tsx I think the following changes would represent more accurately the two descriptions as the frontColor will take up 3/4 of the spinner in line with the docs:

```
backgroundColor: colors.extended.teal100,
frontColor: colors.base.white
```

to:

```
backgroundColor: colors.base.white,
frontColor: colors.extended.teal100
```

**Comment by poteirard** [comment]
Global colors will change soon so I suggest we wait for the new rebranding

**Comment by lluia** [comment]
Closing this issue, for now, it's referenced in [our roadmap](#107) and something we look forward to address soon once we get new design input 🖌
