### ISSUE TITLE
Hardcoded urls in the footer

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#173]
The footer has links which are hardcoded to www.zopa.com.

In shopfront QA uses the footer in UAT to navigate through the site however, they get redirected to the production site.

**Comment by lluia** [comment]
An approach to solve this is to an _optional prop_ :
```jsx
<ZopaFooter baseUrl="https://zopa.com" />
```
If supplied the links will use it as the domain and append their relative to it. Probably we could make it default to `https://zopa.com` so is not a _breaking change_. 

PRs welcome 👍🏻
