### ISSUE TITLE
RadioGroup component?

### ISSUE THREAD

**Issue by thegrinder** [zopaUK/react-components#182]
We do have `<RadioField />` component but it's never really used by itself. There are always a few `<RadioField />`s thrown together to create a field in a form. Hence, the idea of creating `<RadioGroup />` component which would standardise the way these compound fields look and feel

**Comment by lluia** [comment]
This is [gonna be part](https://github.com/zopaUK/react-components/pull/239) of our [next major version `3.0.0`](https://github.com/zopaUK/react-components/pull/233).
