### ISSUE TITLE
Negative <Button /> 🎨

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#19]
![Screenshot 2019-05-28 at 17 02 00](https://user-images.githubusercontent.com/5938217/58489033-c568b180-816a-11e9-8a45-9a62b6d8cbb3.png)

________________________________________

Going through the examples, I’m confused about these variations 👆🏻 of [`<Button />`](https://zopauk.github.io/react-components/#/Components/Atoms?id=button) (  _through `primaryContrast` and `secondaryContrast` props_ ).

It's hard to see the value of customising the text colour through `contrastColor` ( _which anyway should be called `textColor` for clarity ?_ ).

Usually on a design system you just have variations that work against light / dark backgrounds:
```jsx
<Button>Click this!</Button>
<Button negative>Click that!</Button>

/* or... */

<Button>Click this!</Button>
<Button variant="negative">Click that!</Button>
```

This API seems to encourage to pass any text colour to `<Button />` as you wish, which has potential on hurting **Zopa**'s brand 🥺

**Comment by poteirard** [comment]
Let's wait on the new rebranding designs

**Comment by lluia** [comment]
After catching up with the design team, we have 💚 to go ahead with this 👍🏻 
( _hence removing it from **2.0.0**_ )

**Comment by lluia** [comment]
Followed up on #59
