### ISSUE TITLE
Delete icon components 🗑

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#205]
Until now we have been exposing a few components that were in charge to render SVG icons.

However, this was far from providing a proper **icon system**, hence we've decided to remove them and use [**font-awesome**](https://fontawesome.com/v4.7.0/) for iconography internally at Zopa. 

Hence we need to delete as part of `3.0.0`:
- `<Alert />`
- `<Arrow />`
- `<CheckMark />`
- `<Chevron />`
- `<Hamburger />`
- `<Profile />`

and the **"Icons"** section in our live documentation. We'll also need to replace/inline any icons used in other components ( `<Navbar />`, `<AlertBox />` ) ...

**Comment by poteirard** [comment]
Closing as this seems to be done already
