### ISSUE TITLE
Separate form logic from form element

### ISSUE THREAD

**Issue by thegrinder** [zopaUK/react-components#206]
`<Form />` component consists of the `<FormContext.Provider />` and a `<form />` element. I believe it would be a good idea to split them. The reason for this is that if we have a multi step form, we'll need to move up the context but keep the `<form />` tag within each step. It would also solve the issue of nesting 'forms' which right now results in invalid dom nesting warning

**Comment by lluia** [comment]
I believe this was addressed on the above PR ☝🏻 , so closing 👍🏻
