### ISSUE TITLE
Tap targets are not sized appropriately in the footer

### ISSUE THREAD

**Issue by moshie** [zopaUK/react-components#227]
When running a lighthouse check on the Footer component it fails the SEO metric for: "Tap targets are not sized appropriately".

More specifically the Blog and Careers links.

https://web.dev/tap-targets/?utm_source=lighthouse&utm_medium=devtools

> Targets that are smaller than 48 px by 48 px or closer than 8 px apart fail the audit

The Blog link is too small and the Careers link is too close

I propose we increase the margin between items to 8px and make the links display block at mobile?

![Screenshot 2020-02-17 at 12 10 23](https://user-images.githubusercontent.com/3974301/74652717-8f4ae200-517e-11ea-9e78-918a6e25f6ef.png)

**Comment by lluia** [comment]
Seems good to me 👌🏻

**Comment by lluia** [comment]
Addressed on the above PR 🤙🏼
