### ISSUE TITLE
Font licensing restrictions

### ISSUE THREAD

**Issue by grabbeh** [zopaUK/react-components#25]
It looks like the Alverata font has to be directly licensed for a fee (or you access via Adobe Creative Cloud). We should be clearer that if third parties wish to use the Alverata font they will need a direct license to cover their use (especially if in a commercial context). The same goes for Open Sans but at least that's free as it's available in Google Fonts.

We could also make some suggestions for fonts similar to Alverata that are free - I'll have a look.

**Comment by grabbeh** [comment]
I'll update the README and put in a pull request...

**Comment by poteirard** [comment]
this is fixed in #26
