### ISSUE TITLE
Using .displayName for easier debugging

### ISSUE THREAD

**Issue by grabbeh** [zopaUK/react-components#29]
Other component libraries add say ```InputText.displayName = 'InputText'``` for easier debugging as the name of the component will be included in the rendered result. Maybe a thought for this library?

**Comment by lluia** [comment]
@grabbeh good catch 💯

Currently, even when using `styled-components`, we're wrapping them with a named function, which preserves the name on the component during errors:

![Screenshot 2019-06-07 at 11 18 48](https://user-images.githubusercontent.com/5938217/59094282-166c6880-8916-11e9-93f4-7475b2d2935f.png)

and when debugging using the **react-devtools**:

![Screenshot 2019-06-07 at 11 09 53](https://user-images.githubusercontent.com/5938217/59093952-6434a100-8915-11e9-8dab-886e6f31c2b6.png)

However, maybe using `displayName` is a more standardised practice and would avoid us an extra wrapper on the rendered component 💅🏻

What do you think @poteirard? I'm up for it 💪🏻

**Comment by grabbeh** [comment]
Ah serves me right for not using react-devtools. I leave the decision in your capable hands (and I'll turn on react-devtools!).

**Comment by admmasters** [comment]
React's [documentation](https://reactjs.org/docs/react-component.html#displayname) kind of implies you don't need to add it, but if you are specifically wrapping just to add a debuggable name - I'd argue its a better fit.
