### ISSUE TITLE
Remove social media icons 

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#30]
I noticed we have a couple of components ( `<Facebook />` and `<Twitter />`) that render social media icons for **Twitter** and **Facebook**:

<img width="129" alt="Screenshot 2019-06-04 at 17 56 19" src="https://user-images.githubusercontent.com/5938217/58898471-f3b23800-86fa-11e9-8bdc-9fef71c67b40.png">

<img width="131" alt="Screenshot 2019-06-04 at 17 58 13" src="https://user-images.githubusercontent.com/5938217/58898472-f4e36500-86fa-11e9-947e-3ad599d364c6.png">

They're just used within `<ZopaFooter />` and we could _depecrate_ and remove them in upcoming major version?

I can't see the benefit of exporting those to build other stuff 🤔

**Comment by poteirard** [comment]
Related https://github.com/zopaUK/react-components/issues/15
