### ISSUE TITLE
Unify breakpoints and grid breakpoints

### ISSUE THREAD

**Issue by thegrinder** [zopaUK/react-components#300]
Grid breakpoints (https://github.com/zopaUK/react-components/blob/master/src/constants/grid.ts) and the ones found here (https://github.com/zopaUK/react-components/blob/master/src/constants/breakpoints.ts) should probably be unified for consistency sake and to avoid unnecessary confusion

**Comment by lluia** [comment]
Personally, I'm fine with having both separate 💅🏻

Changing the current ones:
```ts
export const breakpoints = {
  desktop: 1280,
  phone: 600,
  tablet: 720,
} as const;
```
Would involve a lof **QA effort**  🙇🏻‍♂️ later for the consumers of this library. They have served us well so I don't see any strong reason to change them.

We could extend them somehow but I think it would end messy? And would be quite tricky to name them as well.

For these questions I think is healthy to ask what are the real issues / needs we're trying to address here for apps consuming the library to justify such a breaking change? 🩺

**Comment by thegrinder** [comment]
You make most of the responsive layouts by using the grid and grid breakpoints, so I'm not sure why we need the other ones. Also, if you try using both grid and non grid breakpoints, elements will collapse at different times

**Comment by lluia** [comment]
> You make most of the responsive layouts by using the grid and grid breakpoints

I think unfortunately at the moment this is not the case. At least in **Savings** we still do heavy use of `minMedia` etc... and I believe in other apps as well.

So again, given the strong impact of this possible **breaking change**, I think it need quite al ot of consideration 💆🏻‍♂️

**Comment by poteirard** [comment]
Fixed in next version
