### ISSUE TITLE
<Modal /> z-index too low

### ISSUE THREAD

**Issue by steedems** [zopaUK/react-components#36]
The Modal [z-index](https://github.com/zopaUK/react-components/blob/ae12f12e2f33456c6d693cc780e2c6bf1fc44124/src/components/molecules/Modal/ModalStyles/ModalStyles.tsx#L12) of `ModalStyles` should probably higher, or the implementation should allow to easily overwrite it. cc @thegrinder 

![Screenshot 2019-06-20 at 15 51 56](https://user-images.githubusercontent.com/7896422/59854714-b6dd7680-9373-11e9-8c68-2ac234b19106.png)

**Comment by lluia** [comment]
A simple API for this would be to _just_ add a `layer` prop:
```jsx
<Modal layer={100}>
  <Other />
</Modal>
```
