### ISSUE TITLE
Typography updates 🔠

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#51]
## Summary

![Screenshot 2019-08-01 at 16 24 51](https://user-images.githubusercontent.com/5938217/62302000-de972280-b479-11e9-93c2-074aa6f5a8ba.png)

New **typographical specs** for our brand.

These updates are meant to be ship as part of the new brand in the [`2.0` milestone](https://github.com/zopaUK/react-components/milestone/1).

## Proposal

I suggested we cover all our typographical needs with two components:
```jsx
/**
 * s = 20px
 * m = 24px [default]
 * l = 28px
 * xl = 48px
 * 
 * line-height: 1.4 
 * weight: 600
 */
<Heading size={'s'|'m'|'l'|'xl'} />

/**
 * s = 12px
 * m = 14px [default]
 * l = 16px
 * 
 * line-height: 1.4 
 */
<Text size={'s'|'m'|'l'} bold={ true | false } />
```
They should cover most type scenarios leveraging the [`as` prop](https://github.com/zopaUK/react-components/issues/24).

## Related issues

- #22 
- #24

**Comment by lluia** [comment]
We need to clarify with the design team:
- _Is really "semibold" the new font for headings? As it differs from Shopfront new pages._
- _When should we use "semibold" over "bold" in body text?_
- _Can we user a relative `line-height` for convenience?_

**Comment by poteirard** [comment]
I'm happy with the implementation. I will also add an example of how to add different html elements like:
```tsx
<Heading size="xl" as="h2" />
```

**Comment by lluia** [comment]
After further discussion, another proposal is to keep the **heading levels** exposed as components ( `Heading1`, `Heading2`, etc... ) which just map internally to `<Heading />`:
```jsx
<Heading1 /> // ... <Heading size={1} as="h1" />
<Heading2 /> // ... <Heading size={2} as="h2" />
<Heading3 /> // ... <Heading size={3} as="h3" />
<Heading4 />  // ... <Heading size={4} as="h4" />

<Label /> // ... <Text as="label />

<Text size={1} />
<Text size={2} />
<Text size={3} bold />
```

**Comment by lluia** [comment]
Finally, we need to have a meeting to decide on the API of this, as few options are open:

## 1. `as` controlled components
```jsx
/**
  Renders: 
    <h1>Loans</h1> ( 48px, bold )
*/
<Heading as="h1">Loans</Heading>

/**
  Renders:
    <h2>Save money with us</h2> ( 28px, bold )
*/
<Heading as="h2">Save money with us</Heading>

/**
  Renders:
    <h3>Save money with us</h3> ( 48px, bold )
    ( Throws warning as usually you're not meant to use `size` on <Heading /> )
*/
<Heading as="h3" size={1}>Save money with us</Heading>

/**
  Renders: 
    <span>Hello</span> ( 16px ) 
    <span>Hello bold</span> ( 14px / bold ) 
    <span>Hello small</span> ( 12px ) 
*/
<Text size={1} as="span">Hello</Text>
<Text size={2} as="span" bold>Hello bold</Text>
<Text size={3} as="span">Hello small</Text>
```

<details>
<summary>Details 📋</summary>
<p>

- The `as` prop is required: you always need to declare which tag it's gonna render.
- Hopefully, it'll force us to use semantic and accessible tags when rendering text 🤞🏻
- `size` is allowed on `<Text />` but throws a warning if used on `<Heading />`
- `bold` can only be used in `<Heading />`

</p>
</details>

<details><summary>Up for it 🙋🏻‍♂️</summary>
<p>

@lluia 

</p>
</details>

## 2. Size named components
```jsx
/**
  Expose component that renders text at a specific size and style
  ( current pattern on the library )
*/

<Heading1>Hello</Heading1>        // <h1>Hello</h1> ( 48px )
<Heading2>Hello</Heading2>       // <h2>Hello</h2> ( 28px )
<Heading3>Hello</Heading3>       // <h3>Hello</h3> ( 24px )
<Heading4>Hello</Heading4>      // <h4>Hello</h4> ( 20px )

<Text1>Foo</Text1>             // <span>Foo</span> ( 16px )
<Text2 as="p">Foo</Text2>     // <p>Foo</p> ( 14px )
<Text3>Foo</Text3>           // <span>Foo</span> ( 12px )
```
<details>
<summary>Details 📋</summary>
<p>

- Expose components which name explictly indicates the size they render text
- You can still leverage the `as` prop on `<Text />` to render different tag
- `as` prop on `<Heading />` is disabled

</p>
</details>


<details><summary>Up for it 🙋🏻‍♂️</summary>
<p>

@lluia 

</p>
</details>


## 3. Generic text and heading components

```
<Heading size={1}>Hello</Heading>        // <h1>Hello</h1> ( 48px )
<Heading size={2}>Hello</Heading>       // <h2>Hello</h2> ( 28px )
<Heading size={3}>Hello</Heading>       // <h3>Hello</h3> ( 24px )
<Heading size={4}>Hello</Heading>      // <h4>Hello</h4> ( 20px )

<Text size={1}>Foo</Text>             // <span>Foo</span> ( 16px )
<Text size={2} as="p">Foo</Text>     // <p>Foo</p> ( 14px )
<Text size={3}>Foo</Text>           // <span>Foo</span> ( 12px )
```
<details>
<summary>Details 📋</summary>
<p>

- Expose single generic `<Text />` and `<Heading />` components
- Their size can be controlled through the `size` prop
- You can leverage the `as` prop to render any other tag

</p>
</details>

<details><summary>Up for it 🙋🏻‍♂️</summary>
<p>

@lluia 

</p>
</details>

**Comment by lluia** [comment]
![Screenshot 2019-08-28 at 15 50 00](https://user-images.githubusercontent.com/5938217/63861651-8fc2a700-c9ab-11e9-9ee7-edb139b5e2e1.png)

☝🏻 latest specs from the design team 🎨

**Comment by lluia** [comment]
![Screenshot 2019-09-18 at 12 14 04](https://user-images.githubusercontent.com/5938217/65139972-d38a5880-da0d-11e9-90b1-4f15f5ebfded.png)

Finally this is what's been implementedm excluding **Heading 0** ( which is only meant for print design at the moment ) downgrading the size of **Headgin 1** on narrow screens to `32px`.
