### ISSUE TITLE
Palette updates 🎨

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#52]
### New colors

![Screenshot 2019-08-02 at 17 22 08](https://user-images.githubusercontent.com/5938217/62552377-d2daa000-b86d-11e9-9ce6-1bc027e53ac7.png)

### Example application

![Screenshot 2019-08-02 at 17 22 15](https://user-images.githubusercontent.com/5938217/62380750-27b6a780-b54a-11e9-8645-2f4598d3479a.png)

## Proposal

We'll need to expose the colors so that client of the library can use them outside of components as needed:

Here's a draft of how the API cool look like?

I believe we'll have two taxonomy levels:
- the colour itself ( `primary` , `secondary` , etc... )
- the variations of the colour ( `lighter` , `darket` , etc... )
```js
import { colors } from '@zopauk/react-components'

colors.primary.basic // → '#00B9A7'
colors.primary.lighter // → '#G0E9A7'
colors.primary.darker //  → '#00G9A7'

colors.secondary.basic // → '#01B9A7'
colors.secondary.lighter // → '#40B9A7'
colors.secondary.darker // → '#90B9A7'

// or can be expressed with arrays too:

colors.primary.basic = '#00B9A7'
colors.primary.shades = [ '#50B9A7' , '#G0E9A7' ,  '#00G9A7' ] // the lower the index the lighter the shade
```

**Comment by poteirard** [comment]
I prefer to make it explicit. Like `colors.secondary.darker` rather than array that it can be confusing and bad for readability.

**Comment by lluia** [comment]
Addressed on [`2.0`](https://github.com/zopaUK/react-components/pull/54) ☝️

**Comment by moshie** [comment]
I was looking into this and was thinking about a helper function to access colours similar to:
```js
color('type', 'shade');
```

My reasoning behind this is the colour api would be more adaptable behind a functional abstraction.

Meaning we could remove colours and add colours without breaking the implementations in any components.

It also it eliminates the need to add basic as a property which is a nice shorthand.

This way could also have fallback colours in the event the colour api was changed for example:
```js
color('opps', 'fail') || 'red'; // red
// ---
colors.opps.fail || 'red' // TYPE ERROR
```
I made a code pen so you could see what I mean: https://codepen.io/moshie/pen/KKPmJzr?editors=0012

**Comment by lluia** [comment]
Hi @moshie, thanks for your suggestion 💯 

I think is something we could consider on a future release 🤔 

This is our new [colour spec](https://github.com/zopaUK/react-components/blob/milestone/2.0/src/constants/colors.ts#L5-L21).

By reading the object directly:
- TS warns at compilet time if you're reading something that doesn't exist. 
- Get auto-complete for free in your editor 
- You don't need to type it as TS can infer it _easily_

I think _getters_ are useful when the object structure behind changes a lot or you don't have control over it. They do introduce challenges around typing and make the API less obvious 🧐

We hope though our **colours won't change in the near future** and stay pretty stable, hence I think we should be fine for now. 

You could open a separate issue though if you think is something we can discuss more 👍🏻

**Comment by moshie** [comment]
Hi @lluia, No problem 👍

The more I think about this the more I am coming around to the object approach, I think I just needed to hear it from someone else.

As you say if the colours aren't going to change too much 🤞 the object approach is way more TS & IDE friendly.

Thanks for the explanation! 👌
