### ISSUE TITLE
ProductTemplate back button extensibility improvement

### ISSUE THREAD

**Issue by rorydpayne** [zopaUK/react-components#637]
Currently, the `ProductTemplate` component allows you to set a `ProductTemplateProps.prevStep?: string | ReactNode` property in order to display a back navigation button at the top of the page. Passing in a `string` generates a default styled `Link` with `href={prevStep}` as per [the example in the docs](https://zrc.netlify.app/#/Components/Templates/Product). Whereas passing in a `ReactNode` completely replaces the link with your own component.

I think this can be improved. In most cases, clients are going to want the default styled link but may well prefer more control by way of a callback function. At the moment, you would have to implement your own styled back button with `onclick` attribute to achieve this which feels wasteful. 

I propose one of the following:

1. Define `prevStep?: string | ReactNode | () => void`  allowing the client to pass in a callback function to be invoked with the default styled link's `onclick` attribute. This is probably the simplest solution and doesn't change the API much beyond diversifying the `prevStep` union type.

2. Define a new `onBackPressed?: (UIEvent) => void` property of `ProductTemplateProps`. This becomes more of an interceptor as the client can still define an href value for `prevStep`. However, there will be an optional extensibility point before that navigation occurs without any routing responsibility. It means you could define something generic like say...
```tsx { "props": { "style": {  "padding": "0" } } }
const onBackPressed = ({ preventDefault }) => {
  if (confirm('Do you want to exit without saving?')) {
    return;
  }
 preventDefault();
};
```
Still not a breaking change but maybe a bit faffy.

3. If there's no appetite for either of the above changes to `ProductTemplate`, then at least we should expose the back button as an extensible component whilst leaving the `ProductTemplate` alone. This way clients don't need to maintain their own styled navigation buttons.
e.g.
```tsx { "props": { "style": {  "padding": "0" } } }
export const BackButton = ({ href, onClick, text = 'Back' }: BackButtonProps) => (
  <StyledLink href={href} onClick={onClick} aria-label={text}>
    <Icon variant={faChevronLeft} color={colors.greyDark} size="xs" className="mr-2" />
    <BackText>{text}</BackText>
  </StyledLink>
);
```

Let me know what you think.

**Comment by JuliaHempel** [comment]
This sounds good to me, I like the first option the best. It will remove a couple of back buttons created in the different project and still let the projects that use nextjs and Gatsby send in their own link.

**Comment by rorydpayne** [comment]
I'm not very familiar with nextJS and gatsby although I'm obviously familiar with frameworks in other languages that render views server-side. I still struggle to imagine a JS framework which is so ideologically opposed to invoking an optional callback on the primary call-to-action of a given component.

Regardless, the current implementation still requires the client to maintain a link component with different text-decoration, colour and alignment to a specific icon in order to match the style guide. Is it not worth at least exposing some extensible `<BackButton/>` or something?

**Comment by poteirard** [comment]
> Regardless, the current implementation still requires the client to maintain a link component with different text-decoration, colour and alignment to a specific icon in order to match the style guide.

According to our design system we have only one way to style the link which is without icon. You can import all the styles by importing`linkStyle` in your Link component, so you don't have to maintain that. If you have a design that differes from that styling that's a breaking change in the current design standarization and it needs another discussion with the designers.

**Comment by rorydpayne** [comment]
I feel like I'm missing something 😕 . I'm talking about this link.
![Screenshot 2020-11-19 at 10 18 47](https://user-images.githubusercontent.com/7081561/99653709-4a2b4780-2a51-11eb-9ff2-07a2907476f1.png)

It's in the library already and widely used - not a new, different design. I'd like to keep the button but hook into the `onclick` which I cannot currently do as it is implemented [like this](https://github.com/zopaUK/react-components/blob/master/src/components/templates/ProductTemplate/ProductTemplateNavigation/ProductTemplateNavigation.tsx#L38-L41).

**Comment by poteirard** [comment]
Ahh true! Even like that, I still think if we allow this you can allow other listeners in the future which will make the component very verbose. Do you know if there are other projects who are facing the same problem as you do?

**Comment by rorydpayne** [comment]
A quick github search turns up [investors-nextgen-web](https://github.dns.ad.zopa.com/zopaUK/investors-nextgen-web/blob/f1d5dc1c8b855615799be9d7ed45b072dbe238bd/packages/web/src/components/BackButton/BackButton.tsx) and [savings-dashboard-web](https://github.dns.ad.zopa.com/zopaUK/savings-dashboard-web/blob/cb985bfbd2f9d5f3e1e866c2fd303feda1a81a65/src/components/BackButton/index.tsx) as both having recreated the back link with chevron for the purpose of hooking into the onclick listener. We would be the third project to do this.

**Comment by poteirard** [comment]
Ok! Sounds good to me then! Feel free to re-open your PR.

**Comment by poteirard** [comment]
Done
