### ISSUE TITLE
Update footer copy

### ISSUE THREAD

**Issue by endymion1818** [zopaUK/react-components#65]
## What is the context?

When we become a bank, we need to align all legal text to mention Zopa Limited and Zopa Bank Limited.

## What needs to be done?

- The copy of the footer component in the React library needs to be updated
- The link structure needs to be updated
- The React component needs to be used in all Shopfront pages

#### FROM

© Zopa Limited 2019 All rights reserved. 'Zopa' and the Zopa logo are trade marks of Zopa Limited. Zopa is a member of CIFAS – the UK's leading anti-fraud association, and we are registered with the Office of the Information Commissioner (No. Z8797078).

Zopa Limited is incorporated in England & Wales (registration number 05197592), with its registered office at 1st Floor, Cottons Centre, Tooley Street, London, SE1 2QG. Zopa Limited is authorised and regulated by the Financial Conduct Authority, and entered on the Financial Services Register under firm registration number 718925.

Contact Zopa on 020 7580 6060. Calls may be monitored or recorded.

#### TO

Zopa Limited is authorised and regulated by the Financial Conduct Authority, and entered on the Financial Services Register (718925). Zopa Bank Limited is authorised by the Prudential Regulation Authority and regulated by the Financial Conduct Authority and the Prudential Regulation Authority, and entered on the Financial Services Register (800542). Zopa Limited (05197592) and Zopa Bank Limited (10627575) are both incorporated in England & Wales and have their registered office at: 1st Floor, Cottons Centre, Tooley Street, London, SE1 2QG.

© Zopa Bank Limited 2019 All rights reserved. 'Zopa' is a trademark of Zopa Bank Limited.

Zopa is a member of Cifas – the UK’s leading anti-fraud association, and we are registered with the Office of the Information Commissioner (ZA275984, Z8797078).

### FROM
![_thumb_30671](https://user-images.githubusercontent.com/2216344/62951631-2e62db80-bde2-11e9-872f-5fd2487e83f5.png)

### TO
<img width="1027" alt="NEW_React_component" src="https://user-images.githubusercontent.com/2216344/62951620-299e2780-bde2-11e9-98f3-cb6780d6b27e.png">

**Comment by lluia** [comment]
I believe this was addressed and released [here](https://github.com/zopaUK/react-components/pull/72).

**Comment by endymion1818** [comment]
Thanks for updating this Lluis!
