### ISSUE TITLE
"squash" vs "merge" on `master` 💅🏻  

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#9]
We're using the default **merge** when merging PRs into the main branch `master` : 

<img src="https://user-images.githubusercontent.com/5938217/58322141-68929180-7e20-11e9-8d80-7e3a1efb3735.png" width="250" />

I suggest we instead [**squash** the commits](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) when we merge PRs in `master` :

<img src="https://user-images.githubusercontent.com/5938217/58322312-d939ae00-7e20-11e9-9abc-22cc4a358cd1.png" width="250" />

The benefits I see is that history is much cleaner and easier to read.

It becomes self-evident which commit comes from a PR and which one not.  It's also easier to `rebase` as you need to traverse less commits.

It can be applied as the _default_ on settings:

<img src="https://user-images.githubusercontent.com/5938217/58322632-cc698a00-7e21-11e9-9784-ee95f5fc9ae7.png" width="250" />

**Comment by poteirard** [comment]
Sounds good to me. I just changed the config of the repo to use only "squash and merge".

If someone has anything against it just re-open this issue :)
